TIME_CREATED = 'TIME_CREATED'
DATA_SET =  'DATA_SET'
DATA_SET1 =  'DATA_SET1'
FREQUENCY = 'FREQUENCY'
REAL_IMPEDANCE ='REAL_IMPEDANCE' 
IMAGINARY_IMPEDANCE ='IMAGINARY_IMPEDANCE' 
LOGARITHMIC_RELAXATION_TIME ='LOGARITHMIC_RELAXATION_TIME'
FUNCTION_PARAMATERS = 'FUNCTION_PARAMATERS'
POPULATION = 'POPULATION'
BEST_MODELS = 'BEST_MODELS'
C_ARRAY = 'C_ARRAY'
FITNESS = 'FITNESS'

ALGORITHIM_RUNNING = 'ALGORITHIM_RUNNING'
PROJECT_STATUS = 'PROJECT_STATUS'

PROJECTS_CONSTANTS = 'PROJECTS_CONSTANTS'

DISCREPANCY='DISCREPANCY'

